# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created: Fri Mar  7 17:23:28 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(829, 752)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 60, 811, 691))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Mono"))
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QtCore.QSize(12, 12))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayoutWidget_3 = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(235, 9, 571, 641))
        self.verticalLayoutWidget_3.setObjectName(_fromUtf8("verticalLayoutWidget_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.infoTable = QtGui.QTableWidget(self.verticalLayoutWidget_3)
        self.infoTable.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.infoTable.setAutoFillBackground(True)
        self.infoTable.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.infoTable.setGridStyle(QtCore.Qt.SolidLine)
        self.infoTable.setRowCount(0)
        self.infoTable.setColumnCount(4)
        self.infoTable.setObjectName(_fromUtf8("infoTable"))
        self.infoTable.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.infoTable)
        self.frame = QtGui.QFrame(self.verticalLayoutWidget_3)
        self.frame.setEnabled(True)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.checkBox = QtGui.QCheckBox(self.frame)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.horizontalLayout_4.addWidget(self.checkBox)
        self.downloadButton = QtGui.QPushButton(self.frame)
        self.downloadButton.setObjectName(_fromUtf8("downloadButton"))
        self.horizontalLayout_4.addWidget(self.downloadButton)
        self.deleteButton = QtGui.QPushButton(self.frame)
        self.deleteButton.setObjectName(_fromUtf8("deleteButton"))
        self.horizontalLayout_4.addWidget(self.deleteButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.comboBox = QtGui.QComboBox(self.frame)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.horizontalLayout_4.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayoutWidget_4 = QtGui.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 211, 641))
        self.verticalLayoutWidget_4.setObjectName(_fromUtf8("verticalLayoutWidget_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.containerNameEdit = QtGui.QLineEdit(self.verticalLayoutWidget_4)
        self.containerNameEdit.setObjectName(_fromUtf8("containerNameEdit"))
        self.verticalLayout_4.addWidget(self.containerNameEdit)
        self.addButton = QtGui.QPushButton(self.verticalLayoutWidget_4)
        self.addButton.setObjectName(_fromUtf8("addButton"))
        self.verticalLayout_4.addWidget(self.addButton)
        self.containerList = QtGui.QListWidget(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.containerList.setFont(font)
        self.containerList.setStyleSheet(_fromUtf8("item: { height : 20px}"))
        self.containerList.setIconSize(QtCore.QSize(32, 32))
        self.containerList.setObjectName(_fromUtf8("containerList"))
        self.verticalLayout_4.addWidget(self.containerList)
        self.line_3 = QtGui.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(220, 10, 20, 641))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 9, 211, 631))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lineEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.searchButton = QtGui.QPushButton(self.verticalLayoutWidget)
        self.searchButton.setObjectName(_fromUtf8("searchButton"))
        self.verticalLayout_2.addWidget(self.searchButton)
        self.groupTree = QtGui.QTreeWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupTree.setFont(font)
        self.groupTree.setAutoFillBackground(True)
        self.groupTree.setStyleSheet(_fromUtf8("item:{height:20px}"))
        self.groupTree.setIconSize(QtCore.QSize(32, 32))
        self.groupTree.setObjectName(_fromUtf8("groupTree"))
        self.groupTree.headerItem().setText(0, _fromUtf8("1"))
        self.groupTree.header().setVisible(False)
        self.verticalLayout_2.addWidget(self.groupTree)
        self.line_2 = QtGui.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(220, 10, 16, 631))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(230, 10, 571, 631))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupTable = QtGui.QTableWidget(self.verticalLayoutWidget_2)
        self.groupTable.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.groupTable.setAutoFillBackground(True)
        self.groupTable.setEditTriggers(QtGui.QAbstractItemView.SelectedClicked)
        self.groupTable.setRowCount(0)
        self.groupTable.setColumnCount(5)
        self.groupTable.setObjectName(_fromUtf8("groupTable"))
        self.groupTable.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.groupTable)
        self.frame2 = QtGui.QFrame(self.verticalLayoutWidget_2)
        self.frame2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame2.setObjectName(_fromUtf8("frame2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.checkBox2 = QtGui.QCheckBox(self.frame2)
        self.checkBox2.setObjectName(_fromUtf8("checkBox2"))
        self.horizontalLayout_2.addWidget(self.checkBox2)
        self.downloadButton2 = QtGui.QPushButton(self.frame2)
        self.downloadButton2.setObjectName(_fromUtf8("downloadButton2"))
        self.horizontalLayout_2.addWidget(self.downloadButton2)
        self.deleteButton2 = QtGui.QPushButton(self.frame2)
        self.deleteButton2.setObjectName(_fromUtf8("deleteButton2"))
        self.horizontalLayout_2.addWidget(self.deleteButton2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.comboBox2 = QtGui.QComboBox(self.frame2)
        self.comboBox2.setObjectName(_fromUtf8("comboBox2"))
        self.comboBox2.addItem(_fromUtf8(""))
        self.horizontalLayout_2.addWidget(self.comboBox2)
        self.verticalLayout_3.addWidget(self.frame2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 811, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.uploadButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.uploadButton.setObjectName(_fromUtf8("uploadButton"))
        self.horizontalLayout.addWidget(self.uploadButton)
        self.showButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.showButton.setObjectName(_fromUtf8("showButton"))
        self.horizontalLayout.addWidget(self.showButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.faceButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.faceButton.setObjectName(_fromUtf8("faceButton"))
        self.horizontalLayout.addWidget(self.faceButton)
        self.freshButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.freshButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.freshButton.setObjectName(_fromUtf8("freshButton"))
        self.horizontalLayout.addWidget(self.freshButton)
        self.line = QtGui.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 40, 771, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Form", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadButton.setText(QtGui.QApplication.translate("Form", "download", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton.setText(QtGui.QApplication.translate("Form", "delete", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Form", "more", None, QtGui.QApplication.UnicodeUTF8))
        self.addButton.setText(QtGui.QApplication.translate("Form", "add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "personal", None, QtGui.QApplication.UnicodeUTF8))
        self.searchButton.setText(QtGui.QApplication.translate("Form", "search", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox2.setText(QtGui.QApplication.translate("Form", "all", None, QtGui.QApplication.UnicodeUTF8))
        self.downloadButton2.setText(QtGui.QApplication.translate("Form", "download", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteButton2.setText(QtGui.QApplication.translate("Form", "delete", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox2.setItemText(0, QtGui.QApplication.translate("Form", "more", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "group", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "public", None, QtGui.QApplication.UnicodeUTF8))
        self.uploadButton.setText(QtGui.QApplication.translate("Form", "upload", None, QtGui.QApplication.UnicodeUTF8))
        self.showButton.setText(QtGui.QApplication.translate("Form", "down/up ui", None, QtGui.QApplication.UnicodeUTF8))
        self.faceButton.setText(QtGui.QApplication.translate("Form", "info", None, QtGui.QApplication.UnicodeUTF8))
        self.freshButton.setText(QtGui.QApplication.translate("Form", "fresh", None, QtGui.QApplication.UnicodeUTF8))

